---
# tasks file for disable_numa

- name: Create the /etc/sysctl.d directory (if necessary)
  file:
    path: /etc/sysctl.d
    state: directory
    mode: 0755

- name: Disable NUMA
  copy:
    dest: /etc/sysctl.d/99-disable-numa.conf
    mode: 0644
    content: vm.zone_reclaim_mode=0
